version: "3"
services:
  redis_test:
    image: "redis:5.0.6"
    ports:
      - "6379:6379"

  mysql_test:
    image: mysql/mysql-server:5.6
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dcui
      MYSQL_USER: dcui
      MYSQL_PASSWORD: dcui
    volumes:
     - /var/lib/mysql

  redis_dev:
    image: "redis:5.0.6"
    ports:
      - "6378:6379"

  mysql_dev:
    image: mysql/mysql-server:5.6
    ports:
     - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dcui
      MYSQL_USER: dcui
      MYSQL_PASSWORD: dcui
    volumes:
     - /var/lib/mysql
